#!/bin/python3

import math
import os
import random
import re
import sys

def designerPdfViewer(h, word):
    # Write your code here
    
    # Find related number for all letters in word
    letterToIndex = {
        "a":0,
        "b":1,
        "c":2,
        "d":3,
        "e":4,
        "f":5,
        "g":6,
        "h":7,
        "i":8,
        "j":9,
        "k":10,
        "l":11,
        "m":12,
        "n":13,
        "o":14,
        "p":15,
        "q":16,
        "r":17,
        "s":18,
        "t":19,
        "u":20,
        "v":21,
        "w":22,
        "x":23,
        "y":24,
        "z":25
    }
    
    indexArray = []
    
    for i in word:
        index = letterToIndex[i]
        indexArray.append(index)
        
    # Save all numbers in an array
    
    sizeArray = []
    
    for i in indexArray:
        sizeArray.append(h[i])
        
        
    area = len(word)*max(sizeArray)
    
    return area
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
